# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-31 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='identification',
            field=models.CharField(max_length=100),
        ),
    ]
